 SLU Moment Tensor Solution
 ENS  2013/09/29 21:23:16:1  40.31    0.78   2.3 3.2 CASTOR
 
 Stations used:
   CA.CBEU CA.CBRU CA.CFON CA.CMAS CA.CORI ES.ECHI ES.EMOS 
   ES.EMUR ES.EQES ES.ERTA ES.ESBB LC.CANF 
 
 Filtering commands used:
   cut o DIST/3.3 -30 o DIST/3.3 +60
   rtr
   taper w 0.1
   hp c 0.03 n 3 
   lp c 0.08 n 3 
 
 Best Fitting Double Couple
  Mo = 5.82e+20 dyne-cm
  Mw = 3.11 
  Z  = 5 km
  Plane   Strike  Dip  Rake
   NP1      146    64   -146
   NP2       40    60   -30
  Principal Axes:
   Axis    Value   Plunge  Azimuth
    T   5.82e+20      3     272
    N   0.00e+00     49     179
    P  -5.82e+20     41       5

 Moment Tensor: (dyne-cm)
    Component   Value
       Mxx    -3.26e+20
       Mxy    -4.83e+19
       Mxz    -2.87e+20
       Myy     5.78e+20
       Myz    -5.05e+19
       Mzz    -2.52e+20
                                                     
                                                     
                                                     
                                                     
                     --------------                  
                 ----------------------              
              ##-------------------------#           
             ###-----------   ------------#          
           #####----------- P -----------####        
          #######----------   -----------#####       
         ########------------------------######      
        ##########----------------------########     
        ##########----------------------########     
         ##########--------------------##########    
       T ###########------------------###########    
         ############----------------############    
       ###############-------------##############    
        ###############-----------##############     
        #################-------################     
         #################-----################      
          ####################################       
           ###############----###############        
             ##########---------###########          
              ###------------------#######           
                 ----------------------              
                     --------------                  
                                                     
                                                     
                                                     
 Global CMT Convention Moment Tensor:
      R          T          P
 -2.52e+20  -2.87e+20   5.05e+19 
 -2.87e+20  -3.26e+20   4.83e+19 
  5.05e+19   4.83e+19   5.78e+20 


Details of the solution is found at

http://www.eas.slu.edu/eqc/eqc_mt/MECH.NA/20130929212316/index.html
